# Generated by Django 4.2.7 on 2023-12-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nail_salon_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beforemadeby',
            old_name='before_made_by',
            new_name='before_made_by_me',
        ),
    ]
