# Generated by Django 4.2.7 on 2023-12-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nail_salon_app', '0002_rename_before_made_by_beforemadeby_before_made_by_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='service_types',
            field=models.ManyToManyField(related_name='types', through='nail_salon_app.CostAndTime', to='nail_salon_app.servicetype'),
        ),
    ]
