# Generated by Django 4.2.7 on 2023-12-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nail_salon_app', '0003_type_service_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costandtime',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='costandtime',
            name='before_made_by',
        ),
        migrations.RemoveField(
            model_name='costandtime',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='costandtime',
            name='type',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.RemoveField(
            model_name='type',
            name='service_types',
        ),
        migrations.RemoveField(
            model_name='visitregistration',
            name='what_to_do',
        ),
        migrations.DeleteModel(
            name='Addons',
        ),
        migrations.DeleteModel(
            name='BeforeMadeBy',
        ),
        migrations.DeleteModel(
            name='CostAndTime',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='VisitRegistration',
        ),
    ]
