# Generated by Django 4.2.7 on 2023-12-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nail_salon_app', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='service_types',
        ),
        migrations.AlterUniqueTogether(
            name='visitregistration',
            unique_together={('date', 'time')},
        ),
    ]
