# Generated by Django 4.2.7 on 2023-12-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nail_salon_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeforeMadeBy',
            new_name='BeforeMadeByMe',
        ),
        migrations.RenameField(
            model_name='addons',
            old_name='addon',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='service_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='name',
        ),
    ]
