# Generated by Django 4.2.7 on 2023-12-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nail_salon_app', '0002_rename_beforemadeby_beforemadebyme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_me', models.BooleanField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BeforeMadeByMe',
        ),
    ]
