# Generated by Django 4.2.7 on 2023-12-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nail_salon_app', '0003_beforemade_delete_beforemadebyme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeforeMade',
        ),
        migrations.RemoveField(
            model_name='costandtime',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='costandtime',
            name='type',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.RemoveField(
            model_name='visitregistration',
            name='addons',
        ),
        migrations.RemoveField(
            model_name='visitregistration',
            name='what_to_do',
        ),
        migrations.DeleteModel(
            name='Addons',
        ),
        migrations.DeleteModel(
            name='CostAndTime',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='VisitRegistration',
        ),
    ]
