# Generated by Django 4.2.7 on 2023-12-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nail_salon_app', '0006_alter_type_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitRegistration',
        ),
    ]
