# Generated by Django 4.2.7 on 2023-12-13 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nail_salon_app', '0007_delete_visitregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('datetime', models.DateTimeField(unique=True)),
                ('addons', models.ManyToManyField(to='nail_salon_app.addons')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nail_salon_app.beforemadeby')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nail_salon_app.quantityofaddons')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nail_salon_app.service')),
            ],
        ),
    ]
