# Generated by Django 4.2.7 on 2023-12-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nail_salon_app', '0008_visitregistration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='LengthType',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='type',
            new_name='length_type',
        ),
    ]
