# Generated by Django 4.2.7 on 2023-12-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nail_salon_app', '0009_rename_type_lengthtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addons',
            name='display_name',
            field=models.CharField(default='yes', max_length=64),
            preserve_default=False,
        ),
    ]
