# Generated by Django 4.2.7 on 2023-12-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nail_salon_app', '0011_remove_addons_display_name_beforemadeby_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitregistration',
            name='addons',
            field=models.ManyToManyField(blank=True, null=True, to='nail_salon_app.addons'),
        ),
    ]
