# Generated by Django 4.2.7 on 2023-12-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nail_salon_app', '0013_alter_visitregistration_addons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitregistration',
            name='addons',
            field=models.ManyToManyField(to='nail_salon_app.addons'),
        ),
    ]
