# Generated by Django 4.2.7 on 2023-12-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nail_salon_app', '0014_alter_visitregistration_addons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitregistration',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
